/**
 * OceanIQ — analysis orchestrator.
 *
 * The single entry point the UI and the REST layer call. It wires the trained
 * model to the decision engines and returns one `AnalysisResult`.
 *
 *   scenario -> forecast -> {timing, port, vessel, route, cost, strategies}
 *            -> {savings, risk, recommendation, alerts, report}
 *
 * Every step is deterministic, so the same scenario always yields the same
 * result — which is what makes the saved-report id meaningful.
 */

import { forecastFreight, getModelDescriptor } from "@/lib/ml/forecastService";
import {
  getExogenousForecast,
  getHistoryMeta,
  getHistorySeries,
} from "@/lib/ml/dataLoader";
import { getPort, PORTS } from "@/lib/reference/ports";
import { getCargo } from "@/lib/reference/cargo";
import { VESSEL_REFERENCE } from "@/lib/reference/corridors";
import { determineCharterTiming } from "./charterTiming";
import { assessPorts } from "./port";
import { corridorDistanceFor, recommendVessel } from "./vessel";
import { optimizeRoutes } from "./route";
import { computeCost } from "./cost";
import { computeSavings } from "./savings";
import { computeRisk } from "./risk";
import { compareStrategies } from "./strategy";
import { buildRecommendation } from "./recommendation";
import { round, stableHash } from "./shared";
import type { AnalysisResult, DataDisclosure, ProcurementScenario } from "@/lib/types";

function scenarioId(scenario: ProcurementScenario): string {
  return stableHash(JSON.stringify(scenario));
}

/** Projected congestion for every candidate discharge port at arrival. */
function congestionProjection(): Record<string, number> {
  const exo = getExogenousForecast();
  const target = Math.min(1, exo.length - 1);
  const week = exo[target];
  const out: Record<string, number> = {};
  for (const port of PORTS) {
    const projected = week?.congestion[port.name];
    out[port.name] =
      typeof projected === "number" ? projected : port.congestionBase;
  }
  return out;
}

function disclosure(): DataDisclosure {
  const meta = getHistoryMeta();
  return {
    datasetKind: "Synthetic / reference dry-bulk freight data",
    trainedOn:
      `Synthetic/reference data — ${meta.rows.toLocaleString()} weekly observations across ` +
      `${getHistorySeries().size} reference lanes (Hay Point, Newcastle, Gladstone, Richards Bay, ` +
      `Saldanha and Tubarao to Paradip, Visakhapatnam, Gangavaram, Gopalpur, Dhamra and Haldia), ` +
      `generated by a structural market model with fixed seed 20260915. ` +
      `Latest reference week ${meta.asOf}.`,
    notTrainedOn: [
      "Live SAIL / RAIL data or any proprietary charter-party fixture",
      "Baltic Exchange Dry Index or any index provider feed",
      "AIS vessel-position or port-call data",
      "Commodity futures curves or weather-model output",
    ],
    costNote:
      "Cost lines are indicative modelled estimates built from reference charter rates, bunker indices and port tariffs. They are not broker quotations and exclude financing, hedging and tax effects.",
    riskNote:
      "Risk scores are a deterministic normalised construct over the model's own forecast band and the reference congestion profile. They are not probabilities and are not calibrated to realised outcomes.",
    savingsNote:
      "Savings are measured against a modelled spot-book baseline at the same corridor and today\'s reference rate. They quantify the modelled effect of the recommended structure, not a guaranteed commercial outcome.",
    recalibrationNote:
      "Re-run `python -m ml.data.generate_reference_data`, `python -m ml.train_model` and `python -m ml.data.generate_exogenous_forecast` after changing any reference assumption; the REST layer reads the regenerated artifacts at process start.",
  };
}

export function runAnalysis(scenario: ProcurementScenario): AnalysisResult {
  const started = Date.now();

  // 1. ML freight forecast --------------------------------------------------
  const forecast = forecastFreight({
    loadingPort: scenario.loadingPort,
    dischargePort: scenario.dischargePort,
    vesselType: scenario.preferredVesselType,
    cargo: scenario.cargo,
  });

  // 2. Timing ---------------------------------------------------------------
  const timing = determineCharterTiming(scenario, forecast);

  // 3. Port feasibility, scored against the stated vessel preference ---------
  const congestionByPort = congestionProjection();
  const congestion = congestionByPort[scenario.dischargePort] ?? getPort(scenario.dischargePort).congestionBase;
  const ports = assessPorts(scenario, scenario.preferredVesselType, congestionByPort, {
    fromDate: forecast.firstForwardDate,
    horizonWeeks: Math.min(8, forecast.forecastHorizonWeeks),
  });

  // 4. Vessel ---------------------------------------------------------------
  const distanceNm = corridorDistanceFor(scenario);
  const vessel = recommendVessel({
    scenario,
    forecast,
    port: ports.selected,
    distanceNm,
    congestion,
  });
  const primaryVessel = vessel.primary.type;
  const vesselRef = VESSEL_REFERENCE[primaryVessel];

  // 5. Route ----------------------------------------------------------------
  // Congestion exposure is re-read for the vessel actually recommended, since a
  // larger class can change how fast it turns around.
  const route = optimizeRoutes({
    scenario,
    vessel: primaryVessel,
    port: ports.selected,
    ratePerDay: vessel.primary.impliedDailyRate,
    congestion,
  });

  // 6. Cost -----------------------------------------------------------------
  const cost = computeCost({
    scenario,
    forecast,
    vessel: primaryVessel,
    port: ports.selected,
    route: route.selected,
    congestion,
  });

  // 7. Contract structures ---------------------------------------------------
  const freightLine = cost.items.find((i) => i.key === "freight")?.perVoyage ?? 0;
  const nonFreight = cost.totalPerVoyage - freightLine;
  const strategies = compareStrategies({
    scenario,
    forecast,
    vessel: primaryVessel,
    port: ports.selected,
    nonFreightCostPerVoyage: nonFreight,
    charterDaysPerVoyage: freightLine / Math.max(1, cost.referenceRatePerDay),
  });
  const selectedStrategy = strategies.find((s) => s.recommended) ?? strategies[0];

  // 8. Savings --------------------------------------------------------------
  // Shares the strategy engine's baseline so the savings screen and the contract
  // screen cannot disagree.
  const savings = computeSavings({
    scenario,
    forecast,
    vessel,
    port: ports.selected,
    cost,
    strategies,
    selectedStrategy,
  });

  // 9. Risk -----------------------------------------------------------------
  const risk = computeRisk({
    scenario,
    forecast,
    vessel,
    port: ports.selected,
    route: route.selected,
    cost,
    strategy: selectedStrategy,
    timing,
  });

  // 10. Brief ---------------------------------------------------------------
  const model = getModelDescriptor();
  const recommendation = buildRecommendation({
    scenario,
    forecast,
    timing,
    vessel,
    port: ports,
    route,
    cost,
    savings,
    risk,
    strategies,
    selectedStrategy,
    model,
  });

  const cargoRef = getCargo(scenario.cargo);
  const assumptions = [
    `Weekly forecast horizon of ${forecast.forecastHorizonWeeks} weeks, projected recursively from the reference history ending ${getHistoryMeta().asOf}.`,
    `Vessel selection weighted 34% physical compatibility, then parcel fit, all-in cost per tonne, availability tightness and scale efficiency.`,
    `Route screening compares three deterministic corridors; the cheapest corridor holding risk at or below the programme tolerance is selected.`,
    `Cost model applies a 14.5% bunker share indexed to the exogenous bunker projection and a 42% demurrage provision on waiting exposure.`,
    `Risk weights: market 26%, port 20%, counterparty 18%, schedule 14%, compliance 12%, liquidity 10%.`,
    `${cargoRef.label} handling, stowage and hazard characteristics follow the reference assumptions in src/lib/reference/cargo.ts.`,
    `Vessel payload ${vesselRef.payload.toLocaleString()} t dwt drives voyages per parcel for a ${scenario.quantity.toLocaleString()} t parcel.`,
  ];

  return {
    scenarioId: scenarioId(scenario),
    scenario,
    totalQuantity: scenario.quantity * scenario.voyages,
    generatedAt: new Date().toISOString(),
    referenceAsOf: getHistoryMeta().asOf,
    model,
    forecast,
    charterTiming: timing,
    vessel,
    port: ports,
    route,
    cost,
    savings,
    risk,
    strategies,
    selectedStrategy,
    recommendation,
    alerts: risk.advisories,
    disclosure: disclosure(),
    assumptions,
    computeMs: round(Date.now() - started, 1),
  };
}